"""empty message

Revision ID: 3021905b0265
Revises: 38cf2db80fd9
Create Date: 2025-11-18 23:00:08.024102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3021905b0265'
down_revision = '38cf2db80fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
