"""empty message

Revision ID: be958b89f0cd
Revises: a5cffa318ac2
Create Date: 2025-10-03 19:55:28.921461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be958b89f0cd'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=20), nullable=False),
    sa.Column('producer', sa.String(length=40), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('opening_crawl', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('climate', sa.String(length=40), nullable=False),
    sa.Column('terrain', sa.String(length=40), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=False),
    sa.Column('crew', sa.String(length=20), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('consumables', sa.String(length=20), nullable=False),
    sa.Column('hyperdrive_rating', sa.String(length=20), nullable=False),
    sa.Column('MGLT', sa.String(length=20), nullable=False),
    sa.Column('starship_class', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=False),
    sa.Column('crew', sa.String(length=20), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('consumables', sa.String(length=20), nullable=False),
    sa.Column('vehicle_class', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('classification', sa.Enum('mammal', 'artificial', 'sentient', 'gastropod', 'reptile', 'amphibian', 'insectoid', 'unknown', name='classification'), nullable=False),
    sa.Column('designation', sa.Enum('sentient', 'non_sentient', 'semi_sentient', 'unknown', name='designation'), nullable=False),
    sa.Column('average_height', sa.Float(), nullable=False),
    sa.Column('skin_colors', sa.String(length=100), nullable=False),
    sa.Column('hair_colors', sa.String(length=100), nullable=False),
    sa.Column('eye_colors', sa.String(length=100), nullable=False),
    sa.Column('average_lifespan_in_years', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('homeworld_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starships_films',
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], ),
    sa.PrimaryKeyConstraint('starship_id', 'film_id')
    )
    op.create_table('vehicles_films',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'film_id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('gender', sa.Enum('masculine', 'femenine', name='gender'), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('hair_color', sa.String(length=20), nullable=False),
    sa.Column('eye_color', sa.String(length=20), nullable=False),
    sa.Column('birth_year', sa.String(length=10), nullable=False),
    sa.Column('homeworld_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters_films',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'film_id')
    )
    op.create_table('characters_starships',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'starship_id')
    )
    op.create_table('characters_vehicles',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters_vehicles')
    op.drop_table('characters_starships')
    op.drop_table('characters_films')
    op.drop_table('characters')
    op.drop_table('vehicles_films')
    op.drop_table('starships_films')
    op.drop_table('species')
    op.drop_table('vehicles')
    op.drop_table('starships')
    op.drop_table('planets')
    op.drop_table('films')
    # ### end Alembic commands ###
