"""empty message

Revision ID: e78fc251d62d
Revises: 2200de7b7f2f
Create Date: 2025-11-18 23:03:27.660454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78fc251d62d'
down_revision = '2200de7b7f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('species_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('species_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
